/// Flutter icons QR
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QR
///      fonts:
///       - asset: fonts/QR.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QR {
  QR._();

  static const _kFontFam = 'QR';
  static const String? _kFontPkg = null;

  static const IconData scan = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generate = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vgo_circle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vgo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
